# Generated by Django 5.0.6 on 2024-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_id', models.CharField(max_length=255)),
                ('off_start', models.DateTimeField()),
                ('off_end', models.DateTimeField()),
                ('off_duration', models.FloatField()),
                ('on_start', models.DateTimeField()),
                ('on_end', models.DateTimeField()),
                ('on_duration', models.FloatField()),
                ('watt', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
