# Generated by Django 5.0.6 on 2024-07-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='user.user')),
            ],
        ),
    ]
