# Generated by Django 5.0.6 on 2024-06-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('time_date', models.DateField()),
                ('watt', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
