# Generated by Django 5.0.6 on 2024-07-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_id', models.CharField(max_length=255)),
                ('time_date', models.DateTimeField()),
                ('volt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amp', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
